### ISSUE TITLE
Sorting the Result

### ISSUE THREAD

**Issue by geoffrey-eisenbarth** [CampbellMG/Trello-Powerups#10]
Any chance that adding a sort option for the resulting checklist is feasible? 

I'm surprised that sorting checklists isn't in native Trello, but based on my searching, doesn't seem any PowerUps offer it either. 

Thanks for the great product, BTW. Very useful :)

**Comment by CampbellMG** [comment]
Hey Geoff, 

Sorry for the late response on this one, I've been a bit flat out.

I'm happy to add a sorting option but I wouldn't want to force people into any one sorting method. Do you think a drop-down under the list selection would be okay? 

I'm thinking it can look like this:

![image](https://user-images.githubusercontent.com/40409896/192123243-865fde57-0fac-4015-a59d-de26a7ee4ed8.png)
![image](https://user-images.githubusercontent.com/40409896/192123238-cbff35f0-ad2c-4404-a253-862cc08adcd9.png)

---

As a secondary thought, I don't think it will be too challenging to create a PowerUp that sorts checklists. I'm assuming nobody else has done this because Trello doesn't offer us an API to move checklist items. We could potentially get around this by deleting the original checklist items and re-adding them in sorted order.

Let me know if you think this would be useful and I can take a look at adding it to this suite.

**Comment by geoffrey-eisenbarth** [comment]
No worries for the delay, thanks for looking into this! I think your idea with the dropdown would be great, although as you said it might be best to just offer it as a separate powerup.

**Comment by CampbellMG** [comment]
Too easy, I think I'll release both as I'm not sure about the repercussions of deleting checklist items at the moment. 

I've got a basic implementation of the sorting option ready here so I'll add the finishing touches, test and let you know once it's deployed.

**Comment by CampbellMG** [comment]
This is deployed and should now be available after a refresh

**Comment by geoffrey-eisenbarth** [comment]
This works wonderfully! Thanks so much :)
